### ISSUE TITLE
Marketing, promotion, and social media

### ISSUE THREAD

**Issue by nicoleslaw** [18F/content-guide#107]
We don't always have time to help partners promote the work we did together after launch—but we could provide overarching guidance on how to think about that well.

**Comment by emileighoutlaw** [comment]
Questions from Content Guild meeting (2/2):

- Would this guidance be for us (18F team?) or partners. Seems like the guide is often a model for other folks rather than advice to them
- Andre confirms that this doesn't overlap with anything that Outreach has created 
- There might be some overlap between this and the work being done on transition guides
- Could save time and give other folks guidance


Perhaps this could be broken into smaller tasks and farmed out to the Writing Lab?

**Comment by emileighoutlaw** [comment]
Per Content Guild meeting (2/2), we think this is closely related to: https://github.com/18F/content-guide/issues/82, and we're going to close this issue in favor of it. We think this is a great thing to work on, though!
