### ISSUE TITLE
Review additional GDS guidance

### ISSUE THREAD

**Issue by nicoleslaw** [18F/content-guide#141]
GDS kindly shared their [content design patterns](https://docs.google.com/document/d/1q0daZrKs_yoNKuWzd_-D3UEsXfQOmTzxOs1VnSmnnrw/edit#) with us. There may be some topics here that we could learn from—flagging for review and discussion.

**Comment by awfrancisco** [comment]
Sections that might be good to discuss:
- Linking to specialist content
- Hand holding the user: not sure we need this in the guide but I certainly see it a lot
- Titles and sub-headers that start with verbs: Our heading guidance could use some expansion beyond good SEO practices
- Times
- Long guides: this would be more for a 18F guides editor rather than content, but I certainly think some of our guides are too long.

**Comment by emileighoutlaw** [comment]
Criteria for completion

- [x] Review GDS guidance and Andre's suggestions
- [ ] Open new issues

**Comment by coreycaitlin** [comment]
@jameshupp Any update on this? Would this be a useful pairing topic?

**Comment by coreycaitlin** [comment]
Notes from coworking on this with @jameshupp:

- Linking to specialist content — our link guidance covers much of this, but the GDS examples are nice; we might evaluate whether we have robust enough examples of good more-info links, perhaps as part of splitting link guidance into its own page
- Hand holding the user: not sure we need this in the guide but I certainly see it a lot — I'm not sure we need to follow this rule as closely, but it might be worth adding a note somewhere in the content guide about watching out for patronizing content
- Titles and sub-headers that start with verbs: Our heading guidance could use some expansion beyond good SEO practices — this depends on the site, and I think we need more flexibility to choose the right thing for the product/site we're working on; we could add a bit more heading guidance about consistency, though
- Times — again, I think project-specific content guides should include this as appropriate
- Long guides: this would be more for a 18F guides editor rather than content, but I certainly think some of our guides are too long — agreed; I also think the "guides" content type is a very different thing in the GDS context than in the 18F context (i.e. we're our primary audience for our own guides; at GDS, guides seem to be user-facing process explanations)

**Comment by jameshupp** [comment]
A few other things we want to look at before deciding whether to open other issues:

- [ ] Introducing examples, including any comments on preference for "for example" or something else, and preferred placement in a sentence.
- [ ] When introducing jargon and its plain meaning is more useful than avoiding it. When do users need to learn the term?
- [ ] When to use ordered or unordered lists, or no list at all.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
