### ISSUE TITLE
Consistent use of italics for word-qua-word styling

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/content-guide#147]
I believe we agreed in the 2016-09-14 meeting that we officially sanction:

> We prefer _public_ to _citizens_.

rather than:

> We prefer “public” to “citizens”.

This issue is to keep track of moving towards the former in the content guide.
- [x] https://pages.18f.gov/content-guide/capitalization/ includes “Form 1040, U.S. Individual Income Tax Return” and I can see arguments both ways for leaving it as is or changing it to _Form 1040, U.S. Individual Income Tax Return_.
- [x] https://pages.18f.gov/content-guide/conscious-style/#nationality includes the sentence `Depending on the situation, you may want to say something like “People who need healthcare” or “People who need to access government services online.”` and it seems we should change those to italics rather than quotations.
- [x] https://pages.18f.gov/content-guide/specific-words-and-phrases/ contains a lot of quoted words and phrases, mostly examples of what not to do.
- [x] https://pages.18f.gov/content-guide/images/ contains a number of quoted phrases, some of which are quotations of user interfaces. We should change those to follow the https://pages.18f.gov/content-guide/technical-and-interface-writing/#interface-elements recommendations.
- [x] https://pages.18f.gov/content-guide/technical-and-interface-writing/#tables has some quoted words that might need to be changed.
- [x] https://pages.18f.gov/content-guide/urls-and-filenames/#link-text quotes “skimming”, and I'm not sure that usage required the quotation marks.
- [x] https://pages.18f.gov/content-guide/urls-and-filenames/#screen-reader-only-text quotes “screenreader only” at one point, which should probably be reworded.

**Comment by coreycaitlin** [comment]
https://pages.18f.gov/content-guide/capitalization/ includes “Form 1040, U.S. Individual Income Tax Return” and I can see arguments both ways for leaving it as is or changing it to _Form 1040, U.S. Individual Income Tax Return_. — changed to italics for consistency with the rest of the page.

https://pages.18f.gov/content-guide/conscious-style/#nationality includes the sentence `Depending on the situation, you may want to say something like “People who need healthcare” or “People who need to access government services online.”` and it seems we should change those to italics rather than quotations. — for this one, quotations felt right, but I can't quite articulate why. Happy to discuss!

https://pages.18f.gov/content-guide/specific-words-and-phrases/ contains a lot of quoted words and phrases, mostly examples of what not to do. — converted most to italics, and removed both italics and quotations for a few where neither was necessary for clarity (mostly simple **this** not that constructions)

https://pages.18f.gov/content-guide/images/ contains a number of quoted phrases, some of which are quotations of user interfaces. We should change those to follow the https://pages.18f.gov/content-guide/technical-and-interface-writing/#interface-elements recommendations. — fixed interface-copy styling but left quotations elsewhere

https://pages.18f.gov/content-guide/technical-and-interface-writing/#tables has some quoted words that might need to be changed. — left quotations

https://pages.18f.gov/content-guide/urls-and-filenames/#link-text quotes “skimming”, and I'm not sure that usage required the quotation marks. — agreed

https://pages.18f.gov/content-guide/urls-and-filenames/#screen-reader-only-text quotes “screenreader only” at one point, which should probably be reworded. — already addressed, as far as I can tell
