### ISSUE TITLE
endorsements

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/content-guide#16]
Add guidance about not talking about specific products we use at 18F? Goes in Trademark and brands maybe?

**Comment by awfrancisco** [comment]
I think that would be a good place for it. Just need a little expansion of that section that basically says it's ok to point to a product or educational resource, but not to say it's the best thing since sliced bread. Also should put something in there about talking about the products we use day to day. Seems to be more of a restriction on that.

**Comment by awfrancisco** [comment]
Addressed in #13
