### ISSUE TITLE
Is it sitemap or site map? And should we put that in the content guide?

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/content-guide#181]
Hello!

I was editing some copy with site map as two words. Thought it looked weird, but 🤷‍♀️ . Brought it to the content minds of #g-content. 

As @coreycaitlin so wonderfully put it,  "a quick search of casual usage in Slack yields only bewilderment and inconsistency." Same with the internet.

So, we're putting it here and on the agenda to come up with a definitive answer.

<3 and thanks
jamie

**Comment by ShawnEklund** [comment]
Two words. The [source](https://blog.hubspot.com/blog/tabid/6307/bid/33580/The-Content-Creator-s-Master-List-of-Commonly-Troublesome-Words.aspx) I'm using doesn't provide reasoning. My shallow reasoning for keeping it two words is that I _think_ it's only used as one word when it's part of [Google's protocol](https://en.wikipedia.org/wiki/Sitemaps) to allow web developers to publish lists of links from across their sites. So "Sitemap" is a name of a service and site map is the list of pages. I admit this is thin.

**Comment by coreycaitlin** [comment]
AP stylebook seems to treat this as 2 words, per @nicoleslaw.

That said, we've occasionally broken with AP for digital terms, where we may be less conservative.

We're going to conduct a brief internal poll and return with results.

**Comment by coreycaitlin** [comment]
Decided! We're breaking from AP here because:

- We found plenty of instances where `sitemap` is used as a non-proper noun.
- We think the single-word version is a little clearer, because it parses as a single noun very quickly (rather than requiring readers to figure out whether "map" is functioning as a noun or verb).
- We found that AP is often a little more conservative in changing standard usage of more technical terms like this, and we're comfortable diverging here because of the technical nature of much of our work.

@nicoleslaw has already made this change, so I'll go ahead and merge and close this issue.
