### ISSUE TITLE
Add site metadescription

### ISSUE THREAD

**Issue by nicoleslaw** [18F/content-guide#200]
Ex:

> How to plan, write, and manage content at 18F.

**Comment by adunkman** [comment]
Just coming by because the site unfolded with a `none` just now for me: 

![image](https://user-images.githubusercontent.com/14930/84394844-73ef6100-abcb-11ea-8182-6685fef21ba5.png)

**Comment by brentryanjohnson** [comment]
Thank you, @adunkman. 

It looks like `index.html` contains the following front matter:

```
---
permalink: /
title: Introduction
layout: none   
excerpt: none
---
```

And here is the `head` include with a conditional that checks for `excerpt` before defaulting to `site.description`. 

```
<meta name="description" content="{% if page.excerpt %}{{ page.excerpt | strip_html | strip_newlines | truncate: 160 }}{% else %}{{ site.description }}{% endif %}">
```

Since `excerpt` is `none` in index, it literally results in `none`.

I'll send up a PR for this soon. Thanks again.
