### ISSUE TITLE
Encourage orgs to adopt a style "stack"

### ISSUE THREAD

**Issue by richardcornish** [18F/content-guide#23]
In most publishing places, there is typically an order of precedence when writing to a particular style. Usually, the order is:
1. In-house style
2. Adopted style guide (18F, Associated Press, Chicago Manual of Style)
3. Dictionary

If following AP, the dictionaries to follow are:
- Webster’s New World College Dictionary (not made by M-W)
- Webster's Third New International Dictionary

If following CMoS, the dictionaries to follow are:
- Merriam-Webster's Collegiate Dictionary
- Webster's Third New International Dictionary

Rather than tell organizations which books to use, I think adding a page to the Content Guide encouraging organizations to adopt their own "stacks" would add clarity to how an organization should publish their text and resolve ambiguities.

**Comment by arvalarva** [comment]
I disagree. Your guidance on heading capitalization alone has caused a stir in my agency. 7 years ago, we followed AP Style stringently. Then 5 years ago, along came a capitalization queen who had us follow AP Style with title case headlines and “Government.” Now, we have a mish-mash of title and sentence case throughout our projects, and the title-case lovers are scared to leave that practice.

There are so many cooks in the kitchen here in the government, the simpler you can make the guidance, and them more you can explain why it is the best practice, the closer we can get to a unified look and feel. Allowing the agencies to pick a stack won’t help 18f meet its goals.

**Comment by jameshupp** [comment]
I apologize, first off, for not addressing this issue until more than a year after it was opened. We’ve now committed regular work time to reviewing, deciding, and acting on content guide issues, so we’ll be getting to more of these in a more timely manner going forward.

The stack is a really interesting idea, but we’ve decided to close this issue without making changes to the guide for a couple reasons.

First, this is a guide to writing content for 18F. We don't intend to treat it as a guide for other organizations in government, or as a guide to creating content guides. So while a stack strikes me as smart, we are trying to avoid that sort of meta-guidance. We don’t currently discuss content design as a discipline in the [18F Partnership Playbook](https://pages.18f.gov/partnership-playbook/), but if we do, this is something we’ll consider there (especially as we’ll have this guide as the first fallback).

Second, we can't really describe our own stack since we don't have one! For a few specific areas of guidance, we acknowledge AP style as a fallback, but we are mindful of competing style guides that may actually be more relevant in other places (for example, GPO’s). We just haven't examined all of those areas that granularly yet. One of the first sentences on our [Content Principles](https://pages.18f.gov/content-guide/content-principles/) page is "Write in a way that suits the situation." At least for now, opting for less rather than more prescription is a better way for us to do that.

That said, we really like when people adapt this guide to their own purposes, [as described in the introduction](https://pages.18f.gov/content-guide/index.html). And we acknowledge several other guides in [References](https://pages.18f.gov/content-guide/references/), so the opportunity to build a stack with this guide as a starting point is available to anyone who wants to do that.
