### ISSUE TITLE
Add single space guidance

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#34]
One space after a period. No exceptions.

**Comment by jameshupp** [comment]
:+1: Do we want to say why? Or just "This is the rule"? I could see going both ways. (The other question is whether Jekyll—our most frequent but not sole platform—collapses spaces whether the writer wants it to or not.)

**Comment by awfrancisco** [comment]
I think we can just state that this is the rule. They why would have to go into monospace fonts and the origin of the double space. I'm not sure how jekyll handles them, but we just run in to a ton of them while editing posts in Google Docs. Takes up editing time.

**Comment by jameshupp** [comment]
Yeah, I actually started a reply to the issue with a paragraph-long example of monospace type explaining the origin, both with and without the double space, as a way of demonstrating what we no longer worry about.

It, uh, started to feel a bit too cheeky for its own good.

**Comment by arvalarva** [comment]
I include a link to a reputable source that addresses the one-space issue, to keep it simple. Too bad the apstylebook.org reference isn’t public, since that would be the logical place to send the audience.

Homehttp://www.apstylebook.com/online/? > AP Stylebookhttp://www.apstylebook.com/online/?do=chapter > Chapter Punctuationhttp://www.apstylebook.com/online/?do=chapter&chapter=PUNCTUATION > Periods (.)

periods (.) Follow these guidelines:
END OF DECLARATIVE SENTENCE: The stylebook is finished.
END OF A MILDLY IMPERATIVE SENTENCE: Shut the door.
Use an exclamation point if greater emphasis is desired: Be careful!
END OF SOME RHETORICAL QUESTIONS: A period is preferable if a statement is more a suggestion than a question: Why don't we go.
END OF AN INDIRECT QUESTION: He asked what the score was.
MANY ABBREVIATIONS: For guidelines, see abbreviations and acronymshttp://www.apstylebook.com/online/index.php?do=entry&id=6. For the form of frequently used abbreviations, see the entry under the full name, abbreviation, acronym or term.
INITIALS: John F. Kennedy, T.S. Eliot (No space between T. and S., to prevent them from being placed on two lines in typesetting.)
Abbreviations using only the initials of a name do not take periods: JFK, LBJ.
ELLIPSIS: See ellipsishttp://www.apstylebook.com/online/index.php?do=entry&id=3540.
ENUMERATIONS: After numbers or letters in enumerating elements of a summary: 1. Wash the car. 2. Clean the basement. Or: A. Punctuate properly. B. Write simply.
PLACEMENT WITH QUOTATION MARKS: Periods always go inside quotation marks. See quotation markshttp://www.apstylebook.com/online/index.php?do=entry&id=2404.
SPACING: Use a single space after a period at the end of a sentence.

**Comment by awfrancisco** [comment]
I know it's not our style guide of reference, but the GPO is linkable and concise on this issue. 

> 2.49. A single justified word space will be used between sentences. 
>       This applies to all types of composition.

**Comment by tadhg-ohiggins** [comment]
https://pages.18f.gov/content-guide/punctuation/#spaces:

> Spaces
> Sentences should always be separated by a single space. Never two spaces.

I think we cover this already and so am closing this issue; chime in if you object.
