### ISSUE TITLE
Names on second reference

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#55]
Add guidance for how we refer to people on second reference, both inside and outside the organization.

**Comment by nicoleslaw** [comment]
Have we talked about using first name on second reference (on the blog and tweets about our work)? This feels more conversational and friendly to me.

If we're talking about partner agency websites, I would default to AP style as we don't want to be more casual than the White House would be, for example.

**Comment by jameshupp** [comment]
I definitely prefer using first names when we're describing our team members and things they say/do. It feels weird to me when our writing reads like journalism: We're not investigating as third parties; we're narrating our own story. Even when we're quoting someone, we're inviting them to be part of the telling more than we're relating second-hand.

Since you mention the White House, one thing that's interesting about their _first_ references is some presumed knowledge. AP's first reference would be `President Barack Obama` but the White House's is always `President Obama`. Their second reference is `the President` (a capitalization practice at which I raise an eyebrow). While we're not part of the White House, we are part of government, and using `Obama` seems weird to me. All the same applies to the VP.

The main GSA blog uses `Administrator Denise Turner Roth` on first reference, `Administrator Roth` on second. But they also refer to Phaedra as `Phaedra` even after she became a commissioner. I wonder if there's something particular for the chief executive of a given organization?

**Comment by emileighoutlaw** [comment]
I know I'm preaching to the choir here, but one of the things I've noticed in my life as a writer is that people are much more likely to refer to women by their first name on second reference than men. 

I'm ¯_(ツ)_/¯  either way on the rule, but I do think clear guidance would help us avoid that icky tendency.

**Comment by tadhg-ohiggins** [comment]
It looks sort-of like consensus that we should:
- Use first names on second reference when writing about our own teams or work, and when writing blog posts and tweets.
- Follow AP style (mostly last names on second reference) otherwise.

Does that seem reasonable?

**Comment by kategarklavs** [comment]
This seems reasonable to me! One thing to consider (re: writing about our own team): What should our policy be if we're writing about two people with the same first name? (Doesn't seem like this would come up too too often, though I imagine the situation might arise every so often, and it might be good if we have a policy in place for when it does.)

**Comment by tadhg-ohiggins** [comment]
Further apparent consensus from Slack discussion:

If there's a chance of confusion on second reference due to the first name being shared by multiple people being referred to, use their full name. (That is, instead of the options of using only last name, or first name plus last initial.)

**Comment by kategarklavs** [comment]
That works for me!

**Comment by tadhg-ohiggins** [comment]
Okay, last question before writing it up: where in the guide should this go?

**Comment by awfrancisco** [comment]
I think specific words and phrases.

**Comment by jameshupp** [comment]
Structurally it's an awkward fit there, though. I kind of wonder whether it shouldn't be its own page under `Our style`? Or if `Names and titles` should be the page, and we pull the title section out of `Capitalization`?

**Comment by kategarklavs** [comment]
As discussed during our 10/19 guild meeting, we'll move this conversation over to the channel and (we hope) make a decision at our next meeting — stay tuned!

**Comment by emileighoutlaw** [comment]
As a first iteration, we'll be including this guidance under _N_ in _Specific words and phrases_

**Comment by coreycaitlin** [comment]
Hi @tadhg-ohiggins — any update on this? lmk if you'd like to un-assign yourself, and someone else can pick it up when they have time.

**Comment by coreycaitlin** [comment]
This may not belong in _Specific words and phrases_ — we're going to try making a new section, albeit brief.

**Comment by nicoleslaw** [comment]
Relates to #178, @tadhg-ohiggins I will follow up with an alternate idea!

**Comment by coreycaitlin** [comment]
This is resolved with #178 🎉
