### ISSUE TITLE
URLs Should Never Stop Working: I think at some point they should

### ISSUE THREAD

**Issue by thecapacity** [18F/content-guide#71]
The language in there makes it sound like a "forever and ever" rule, but I would propose that ever a period of time with enough status codes (e.g. 301) then at some point the URLs should be sunset. This should also be driven by usage data, i.e. if you haven't had a hit on a URL after (x) years it's probably ok to retire.

This is in direct relation to a situation I've seen an agency "endure" where they maintain very out-dated URLs, including SSL certificates and redundant systems just to preserve a very legacy structure.

**Comment by tadhg-ohiggins** [comment]
I'm in favor of the “forever” rule. Yes, if there are situations where you have to maintain SSL certs for domains you don't use anymore, I can see the argument for eliminating them—but that's a relatively rare case. I'd prefer to keep the notion that URLs are forever (particularly at the stage when people are creating them) foremost than to add language noting the few exceptions.

**Comment by thecapacity** [comment]
I definitely feel like viewing "URLs as forever" breaks the paradigms of HTTP/REST/... i.e. they wouldn't have status codes if the URLs couldn't move. And URLs can represent transient resources that are not supposed to be long-lived... For example Google's use for photos: http://www.theverge.com/2015/6/23/8830977/google-photos-security-public-url-privacy-protected

And it limits agency's abilities to consolidate domains, or modernize sites... i.e. it helps perpetuate old URLs and decentralized web-presence.

Not sure if I'm alone on this, but definitely don't think it's "relatively rare" in practice.

**Comment by konklone** [comment]
I think you might be talking about two different things?

Anyone should be fine moving their content around as long as there's a 301 redirect in place. It's okay if `http://www.iab.net/iablog/2015/03/adopting-encryption-the-need-for-https.html` redirects to `http://www.iab.com/adopting-encryption-the-need-for-https/`, with a 301 and `<link rel="canonical">` and all that.

Closing an entire domain is more severe, because there's no opportunity to send a 301 redirect. Links will just break. For domains which host significant content which should have a permalink, the argument for closing the domain would have to be **very** strong, more than just having it be annoying to keep a certificate up to date.

In terms of certificate maintenance, HTTPS has pushed agencies to consolidate their domains and limit their DNS to fewer "levels" of subdomains, which I think is pretty healthy. But the domains they're getting rid of are mostly content-free -- "convenient" redirectors, or applications that were there for (often legacy) functionality rather than providing content. The argument for closing those down doesn't need to be as strong as removing content from the internet.

**Comment by tadhg-ohiggins** [comment]
If we want to introduce something about different rules for transient content, I'm okay with that. This section was written with URLs for content in mind, not for API endpoints or for other resources. But if you put up an article or guide, the expectation should be that the URL for it will work forever.

As for consolidation, redirects are fine for that—but the old URLs should redirect to the new ones. I don't support breaking user bookmarks (and search engines) because of organizational concerns.

**Comment by konklone** [comment]
> As for consolidation, redirects are fine for that—but the old URLs should redirect to the new ones. I don't support breaking user bookmarks (and search engines) because of organizational concerns.

Of course. For example, `http://www.iab.net/iablog/2015/03/adopting-encryption-the-need-for-https.html` should **not** redirect to `http://www.iab.com` (the home page).

**Comment by thecapacity** [comment]
In the google image example that is a prior known as transient (to a degree) but what about the website consolidation use case, or what about when someone leaves an agency (and perhaps their bio is by name or for a position no longer valid).

The web changes, and I agree it shouldn't suddenly break but nor should we inflict perpetual support for a legacy structure. 

I'd argue the intent is to protect against sudden breakage and I get that aspiration, so I think we should explain that - not distaste a solution to the symptom. 

When one agency I know changed CMS' it was impractical to support the old URLs forever. so there was a grace period and an old.agency.gov and then at some point in time (years later) the old was taken down so there wasn't a perception that it was still valid. 

I think it's important to make sure the rule expresses intent and accepts reality (I.e. Maybe it's ok for the agency to take down the site if it's appropriately archived in the Wayback Machine) and makes sure we don't set up something that might be used as a rule against modernization.

**Comment by tadhg-ohiggins** [comment]
When someone leaves an agency their bio should show their time at the agency; I don't see why a 404 is the right response to encourage. Bios do seem like another edge case.

The scenario of URLs breaking when a CMS changes is precisely what I want to discourage. There are relatively easy ways to support redirects from old URLs to new ones. If those ways are technically impossible, then there's no option but to break the old URLs—but at least we can strongly push in the direction of making sure the _new_ CMS uses URLs that are designed to last forever. The same goes for consolidation—these are organizational changes, and I see no good reason why organizational changes should result in breakage for users.

I do not think the Wayback Machine should be used as a reason to drop responsibility for URLs. If the content that was at the URL is still valid, it should redirect to the newer URL; if it needs updating, it should redirect to the newer URL with newer content; if it's now somehow entirely meaningless, it should redirect to the newer URL with a message to that effect.

These are guidelines, best practices, and not rules. If the technical cost of supporting a set of URLs becomes too great, then the reality is they'll end up being dropped. That this happens does not make it a practice we should encourage.

All this being said, in the content guild we've talked this over and intend to alter the section to a) include more of the reasons for why URLs should be permanent, b) make clear that that's an ideal, and c) be sympathetic to people who are stuck in situations where they cannot meet that ideal.

**Comment by thecapacity** [comment]
Thanks @tadhg-ohiggins I think the clarity on the "all rules can be broken for the right reasons" and clarifying the intent of the ideal will be a big clarification.

**Comment by coreycaitlin** [comment]
Hopefully #166 will help add practical clarity and nuance here — do we need to keep this issue open, as well, or does this conversation and the new "maintaining content" page help address the concern?

**Comment by tadhg-ohiggins** [comment]
My feeling is that #166 will provide enough guidance to close this issue.

**Comment by coreycaitlin** [comment]
Closing this issue, now that we've built out some guidance about maintaining content in general.
