### ISSUE TITLE
Add guidance for mass emails/newsletters

### ISSUE THREAD

**Issue by awfrancisco** [18F/content-guide#82]
More people are moving their email lists to MailChimp and are creating new lists of users of our products. They have been asking for guidance on 18F style for emails. Our content guidance could include:
- Subject line, header, and from best practices
- Newsletter specific tone
- Image, media, and video embedding guidance
- Length an organization guidance
- Strategies for responding

**Comment by kategarklavs** [comment]
I love it! Let me know if you'd like any help with writing or editing :)

**Comment by nicoleslaw** [comment]
Useful reference: http://styleguide.mailchimp.com/writing-email-newsletters/

**Comment by emileighoutlaw** [comment]
Questions from Content Guild meeting (2/2):

- Would this guidance be for us (18F team?) or partners. Seems like the guide is often a model for other folks rather than advice to them
- Andre confirms that this doesn't overlap with anything that Outreach has created 
- There might be some overlap between this and the work being done on transition guides
- Could save time and give other folks guidance


Perhaps this could be broken into smaller tasks and farmed out to the Writing Lab?

**Comment by coreycaitlin** [comment]
Is this still worth writing, or could we point to DigitalGov and/or Mailchimp resources on this?

**Comment by awfrancisco** [comment]
I think we should point to something for now. @Dahianna is working on something tangental for Outreach that we could include later, but a link is a good MVP. And to encourage people to consider the specifics of the medium they choose to communicate.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
